### PR TITLE
add myrattata and bexxxxxxx to credits

### PR DESCRIPTION
**Pull request by Felk**
as requested in July, see also https://cdn.discordapp.com/attachments/855829612037406741/891016638911094824/image0.png
Bex requested to be credited as "BEXXXXXXX" instead

### CODE REVIEW

**Comment by aaaaaa123456789** [comment]
Does this compile? Looks like undefined constants to me.

**Comment by Felk** [comment]
Oh I didn't know those were constants. I knew I shouldn't have tried :(

**Comment by Felk** [comment]
Can someone build that and link or DM me a ROM so I can test it? That would be preferable to setting up a build environment locally

**Comment by Felk** [comment]
Cannot build because:
- f27c9c6a blew the ROMX section size:
  ```
  rgbasm -Weverything -Wno-shift -L -o gfx/pics.o gfx/pics.asm
  rgblink -p 0xff -n chattycrystal.sym -m chattycrystal.map -l chattycrystal.link -o chattycrystal.gbc audio.o home.o main.o wram.o data/text/common.o data/maps/map_data.o data/pokemon/dex_entries.o data/pokemon/egg_moves.o data/pokemon/evos_attacks.o engine/movie/credits.o engine/overworld/events.o gfx/pics.o gfx/sprites.o
  error: chattycrystal.link(305): Sections would extend past the end of ROMX ($800a > $7fff)
  make: *** [Makefile:80: chattycrystal.gbc] Error 1
  ```
- d62ddd4f blew the "Pics 10" section size:
  ```
  rgbasm -Weverything -Wno-shift -L -o gfx/pics.o gfx/pics.asm
  ERROR: gfx/pics.asm(273):
      Section 'Pics 10' grew too big (max size = 0x4000 bytes, reached 0x4020).
  error: Assembly aborted (1 error)!
  make: *** [Makefile:74: gfx/pics.o] Error 1
  ```

**Comment by Felk** [comment]
rebased onto d6bccf98 because those compile issues are none of my business for now

**Comment by Felk** [comment]
credits
looks good?

**Comment by aaaaaa123456789** [comment]
Myrattata should be myRattata, but it's otherwise fine. How hard it is to
rebase onto master? I'll fix the space issues.

**Pull request merged**
